name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build

  docker-build-push:
    needs: lint-test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend image
        run: |
          docker build -f Dockerfile.backend -t ghcr.io/${{ github.repository }}/studio-backend:latest .
          docker push ghcr.io/${{ github.repository }}/studio-backend:latest
      - name: Build and push frontend image
        run: |
          docker build -f Dockerfile.frontend -t ghcr.io/${{ github.repository }}/studio-frontend:latest .
          docker push ghcr.io/${{ github.repository }}/studio-frontend:latest
